name: Maven Central Release
on:
  push:
    branches: ["*"]
    tags: ["*"]

jobs:
  maven_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - uses: olafurpg/setup-scala@v14
      - uses: olafurpg/setup-gpg@v3

      - name: Publish artifacts to Maven Central
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
