name: Check and Deploy

on:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:
    branches:
      - "main"

jobs:
  sbt-build:
    uses: ./.github/workflows/_sbt_build.yml
    with:
      target-os: >-
        ["ubuntu-latest"]
      java-versions: >-
        ["11"]
      preserve-cache-between-runs: true
  maven-release:
    uses: ./.github/workflows/maven_release.yml
    needs: sbt-build
    secrets: inherit
  deploy-docs:
    uses: ./.github/workflows/deploy_docs.yml
    needs: sbt-build
    # Only update Github Pages if this is a release tag
    if: startsWith(github.ref, 'refs/tags/v')