name: Check and Deploy

on:
  push:
    branches: ["*"]
    tags: ["*"]

jobs:
  sbt-build:
    uses: ./.github/workflows/_sbt_build.yml
    with:
      target-os: >-
        ["ubuntu-latest"]
      java-versions: >-
        ["11"]
      preserve-cache-between-runs: true
  maven-release:
    uses: ./.github/workflows/maven_release.yml
    needs: sbt-build
    secrets: inherits
  deploy-docs:
    uses: ./.github/workflows/deploy_docs.yml
    needs: sbt-build
    # Only update Github Pages if this is a push to main
    if: github.ref_type == 'branch' && github.ref_name == 'main'